@echo off
Reg.exe delete "HKLM\System\ControlSet001\Services\storahci\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\umbus\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe add "HKLM\System\ControlSet001\Services\USBHUB3\Parameters" /v "DmaRemappingCompatible" /t REG_DWORD /d "2" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\USBXHCI\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\vdrvroot\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\vwifibus\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\WpdUpFltr\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\WUDFWpdFsParameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\xinputhid\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\ACPI\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\acpipagr\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\BasicDisplay\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\BasicRender\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\dc1-controller\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\EhStorClass\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\HDAudBus\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\intelpep\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\intelppm\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\kbdclass\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\kbdhid\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\MEIx64\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\monitor\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\mouhid\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\msisadrv\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\NdisVirtualBus\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\NdisWan\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\NvModuleTracker\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\partmgr\Parameters" /v "DmaRemappingCompatible" /f
Reg.exe delete "HKLM\System\ControlSet001\Services\pci\Parameters" /v "DmaRemappingCompatible" /f
