@echo off
rem Under Benchmarking
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "CreateGdiPrimaryOnSlaveGPU" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DriverSupportsCddDwmInterop" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddSyncDxAccess" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddSyncGPUAccess" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddWaitForVerticalBlankEvent" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCreateSwapChain" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkFreeGpuVirtualAddress" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkOpenSwapChain" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkShareSwapChainObject" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkWaitForVerticalBlankEvent" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkWaitForVerticalBlankEvent2" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "SwapChainBackBuffer" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "TdrResetFromTimeoutAsync" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "CreateGdiPrimaryOnSlaveGPU" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DriverSupportsCddDwmInterop" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddSyncDxAccess" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddSyncGPUAccess" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddWaitForVerticalBlankEvent" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCreateSwapChain" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkFreeGpuVirtualAddress" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkOpenSwapChain" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkShareSwapChainObject" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkWaitForVerticalBlankEvent" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkWaitForVerticalBlankEvent2" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "SwapChainBackBuffer" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "TdrResetFromTimeoutAsync" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED9" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED10" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED11" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED12" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED13" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED14" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED15" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED16" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED17" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED18" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED19" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED20" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED21" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED22" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED23" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED24" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED25" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED26" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED27" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED28" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED29" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED30" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_RESERVED31" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVA_FILMGRAINBUFFER" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DXVACOMPBUFFER_MAX" /t REG_DWORD /d "8" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "CreateGdiPrimaryOnSlaveGPU" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DriverSupportsCddDwmInterop" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddSyncDxAccess" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddSyncGPUAccess" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddWaitForVerticalBlankEvent" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCreateSwapChain" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkFreeGpuVirtualAddress" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkOpenSwapChain" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkShareSwapChainObject" /t REG_DWORD /d "1" /f
:: Reg.exe adReg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "CreateGdiPrimaryOnSlaveGPU" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DriverSupportsCddDwmInterop" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddSyncDxAccess" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddSyncGPUAccess" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCddWaitForVerticalBlankEvent" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkCreateSwapChain" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkFreeGpuVirtualAddress" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkOpenSwapChain" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkShareSwapChainObject" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkWaitForVerticalBlankEvent" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkWaitForVerticalBlankEvent2" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "SwapChainBackBuffer" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "TdrResetFromTimeoutAsync" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkWaitForVerticalBlankEvent" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "DxgkWaitForVerticalBlankEvent2" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "SwapChainBackBuffer" /t REG_DWORD /d "1" /f
:: Reg.exe add "HKLM\SYSTEM\CurrentControlSet\Services\DXGKrnl" /v "TdrResetFromTimeoutAsync" /t REG_DWORD /d "1" /f

