@echo off
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\rundll32.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\bdeunlock.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\bdechangepin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ClipDLS.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ScriptRunner.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ApplySettingsTemplateCatalog.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Microsoft.Uev.CscUnpinTool.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\UevAppMonitor.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Microsoft.Uev.SyncController.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\chgport.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\chgusr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\query.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\logoff.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qappsrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qprocess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\reset.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\rwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tscon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tsdiscon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tskill.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\msg.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\baaupdate.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\logagent.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mfpmp.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\PackageInspector.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\manage-bde.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\PresentationSettings.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\AgentService.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\repair-bde.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ClipRenew.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\gpscript.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\CustomShellHost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\AssignedAccessGuard.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mavinject.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\BitLockerDeviceEncryption.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\rdpinit.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\rdpshell.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\AppVClient.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\BdeHdCfg.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\CameraSettingsUIHost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\RemoteAppLifetimeManager.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\rdpsign.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\fveprompt.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\iotstartup.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\fvenotify.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\WPDShextAutoplay.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\BdeUISrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wbadmin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wbengine.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\bootim.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\WinBioDataModelOOBE.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\PresentationHost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\rstrui.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\srdelayed.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SrTasks.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SpaceAgent.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\provlaunch.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\EduPrintProv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\UNP\UNPUXHost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\UNP\UNPUXLauncher.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\UNP\UpdateNotificationMgr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Spectrum.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SIHClient.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\xwizard.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\takeown.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\vssadmin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\where.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\cacls.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\eventcreate.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\fsavailux.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ftp.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\grpconv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\runas.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\systeminfo.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\taskkill.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tasklist.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\timeout.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\waitfor.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\whoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mstsc.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\TSTheme.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wkspbroker.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\TSWbPrxy.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\RdpSa.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\RdpSaProxy.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\RdpSaUacHelper.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\sessionmsg.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\TieringEngineService.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\rdpclip.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\rdpinput.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\TapiUnattend.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\dialer.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tcmsetup.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\MultiDigiMon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tabcal.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\FsIso.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\dvdplay.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\calc.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\charmap.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\credwiz.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\certreq.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\certutil.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\klist.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ksetup.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\nltest.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\regini.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\regsvr32.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\setspn.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\regedt32.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ResetEngine.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SysResetErr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\systemreset.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SystemResetPlatform\SystemResetPlatform.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\migwiz\mighost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\pwlauncher.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\fodhelper.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Fondue.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\OptionalFeatures.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\CheckNetIsolation.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\msiexec.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mblctr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\msconfig.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mmc.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\WindowsActionDialog.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\cliconfg.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\odbcad32.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\odbcconf.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\iscsicpl.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\iscsicli.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\IESettingSync.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ie4uinit.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ie4ushowIE.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\F12\IEChooser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ieUnatt.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\iexpress.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wextract.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mshta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wiaacmgr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wiawow64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\bridgeunattend.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\eventvwr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\gpresult.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\gpupdate.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\esentutl.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\eudcedit.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wecutil.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\easinvoker.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\EhStorAuthn.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DpiScaling.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Dxpserver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DeviceProperties.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DisplaySwitch.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SystemSettingsRemoveDevice.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SyncHost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DevicePairingWizard.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ComputerDefaults.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DataExchangeHost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\CompMgmtLauncher.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\convert.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\find.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ktmutil.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\label.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\openfiles.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\replace.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Robocopy.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\takeown.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\vssadmin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\where.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\cacls.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\eventcreate.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\fsavailux.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ftp.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\grpconv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\runas.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\systeminfo.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\taskkill.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tasklist.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\timeout.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\waitfor.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\whoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mstsc.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\TSTheme.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wkspbroker.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\TSWbPrxy.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\RdpSa.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\RdpSaProxy.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\RdpSaUacHelper.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\sessionmsg.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\TieringEngineService.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\rdpclip.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\rdpinput.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\TapiUnattend.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\dialer.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tcmsetup.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\MultiDigiMon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tabcal.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\FsIso.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\dvdplay.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\calc.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\charmap.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\credwiz.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\certreq.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\certutil.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\klist.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ksetup.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\nltest.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\regini.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\regsvr32.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\setspn.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\regedt32.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ResetEngine.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SysResetErr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\systemreset.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SystemResetPlatform\SystemResetPlatform.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\migwiz\mighost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\pwlauncher.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\fodhelper.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Fondue.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\OptionalFeatures.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\CheckNetIsolation.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\msiexec.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mblctr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\msconfig.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mmc.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\WindowsActionDialog.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\cliconfg.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\odbcad32.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\odbcconf.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\iscsicpl.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\iscsicli.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\IESettingSync.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ie4uinit.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ie4ushowIE.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\F12\IEChooser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ieUnatt.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\iexpress.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wextract.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mshta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wiaacmgr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wiawow64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\bridgeunattend.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\eventvwr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\gpresult.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\gpupdate.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\esentutl.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\eudcedit.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wecutil.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\easinvoker.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\EhStorAuthn.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DpiScaling.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Dxpserver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DeviceProperties.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DisplaySwitch.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SystemSettingsRemoveDevice.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SyncHost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DevicePairingWizard.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ComputerDefaults.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DataExchangeHost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\CompMgmtLauncher.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\convert.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\find.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ktmutil.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\label.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\openfiles.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\replace.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Robocopy.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\stordiag.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\choice.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\clip.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\doskey.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\forfiles.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\print.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\subst.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\cttune.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\cttunesvr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\help.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\msdtc.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\CastSrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\UserDataSource.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\curl.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tar.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\spaceman.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\spaceutil.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\EDPCleanup.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\MDMAppInstaller.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ARP.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\finger.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\HOSTNAME.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\MRINFO.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\NETSTAT.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ROUTE.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\sort.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\TCPSVCS.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\xcopy.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\auditpol.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mountvol.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\net.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\net1.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\netsh.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\PATHPING.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\PING.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\reg.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\sc.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\setx.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\TRACERT.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\attrib.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ClipUp.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\diskusage.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\findstr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\icacls.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ipconfig.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\whoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\whois.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ping6.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\robocopy1.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\sscore.dll" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\sscore_ext.dll" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wsqmcons.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ssText3d.scr" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ssText.scr" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\PerfMon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\pnputil.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\msra.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\scregedit.wsf" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ConnectToBluetoothDevices.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DeviceEject.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DisplaySwitch.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\dmcmnutils.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mmc.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\DeviceProperties.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\EhStorShell.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\FileHistory.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\helpPane.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\InstallUtil.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\irftp.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Makecab.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mip.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\mscmsgs.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\notepad.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\oobe\windeploy.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\PrintIsolationHost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Regedt32.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\regsvr32.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\reset.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\RunLegacyCPLElevated.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\sethc.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\sfc.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\sfc_os.dll" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\sigverif.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\spinstall.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\spsys.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\srdelayed.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SSDMCleanup.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\stikynot.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\syncappvpublishingserver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\SyncHost.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Taskmgr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tquery.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tshark.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\taskkill.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\arp.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tsdiscon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tstcon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tswpfwrp.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\typeperf.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\ulsdiag.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\Volumeid.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\vsjitdebugger.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\waitfor.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\waitfor.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\winrs.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\WinSat.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wlrmdr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wpr.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\time.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\timeout.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\tkprof.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\pnputil.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\dpapimig.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\setreg.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\verifier.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\wininit.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\WindowsAnytimeUpgrade.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\winrs.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qprocess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qappsrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qgrep.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qlogin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quserex.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qusergroup.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quserinit.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qusersecl.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quserser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quserver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlog.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\quser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwhoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinlogon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinlogon64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinlogonext.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinlogonext64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwhoami64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinsta64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwhois.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qusergroup.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qusergroup64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\quserinit.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\quserinit64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qusersecl.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qusersecl64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\quserser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\quserser64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\quserver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\quserver64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinlog.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinlog64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinlogon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinlogon64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinlogonext.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinlogonext64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwhoami64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwinsta64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsbin\qwhois.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qprocess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qappsrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qgrep.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qlogin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsession.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhois.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qprocess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qappsrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qgrep.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qlogin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsession.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhois.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qprocess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qappsrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qgrep.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qlogin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsession.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhois.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qprocess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qappsrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qgrep.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qlogin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsession.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhois.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qprocess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qappsrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qgrep.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qlogin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsession.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhois.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qprocess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qappsrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qgrep.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qlogin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsession.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhois.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qprocess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qappsrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qgrep.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qlogin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsession.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhois.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qprocess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\quser.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qappsrv.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qgrep.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qlogin.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsession.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qsess.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogon64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinlogonext64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinver.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhoami64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwinsta64.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qwhois.exe" /f
Reg.exe delete "HKCU\Software\Microsoft\DirectX\UserGpuPreferences" /v "C:\Windows\System32\qprocess.exe /f



