@echo off
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ1Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ6Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ7Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ8Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ16Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ25Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ36Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ39Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ55Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ57Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ1024Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967253Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967254Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967256Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967257Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967258Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967259Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967260Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967261Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967262Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967287Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967288Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967289Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967290Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967291Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967292Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967293Priority" /f
Reg.exe delete "HKLM\System\CurrentControlSet\Control\PriorityControl" /v "IRQ4294967294Priority" /f