@echo off
 Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "AdjustedNullSessionPipes" /t REG_DWORD /d "3" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "AdjustedNullSessionPipes" /t REG_DWORD /d "3" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "autodisconnect" /t REG_DWORD /d "15" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "autodisconnect" /t REG_DWORD /d "15" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "autodisconnect" /t REG_DWORD /d "4294967295" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "AutoShareServer" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "AutoShareWks" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "AutoShareWks" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "DeadGWDetectDefault" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "DefaultRCVWindow" /t REG_DWORD /d "94258" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "DefaultTTL" /t REG_DWORD /d "100" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "DisableBandwidthThrottling" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "DisableCompression" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "DisablePagingExecutive" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "DisableStrictNameChecking" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "DisableTaskOffload" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "DisableTaskOffload" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "DiskSpaceThreshold" /t REG_DWORD /d "5" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "DnsPriority" /t REG_DWORD /d "1469" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "DontAddDefaultGatewayDefault" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "EnableAuthenticateUserSharing" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "EnableAuthenticateUserSharing" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "EnableDCA" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "EnableForcedLogoff" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "enableforcedlogoff" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "EnableICMPRedirect" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "EnableOplocks" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "EnablePMTUBHDetect" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "EnablePMTUBHDetect" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "EnablePMTUDiscovery" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "EnableSecuritySignature" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "enablesecuritysignature" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "EnableTCPA" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "EnableWsd" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "GlobalMaxTcpWindowSize" /t REG_DWORD /d "65535" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "GlobalMaxTcpWindowSize" /t REG_DWORD /d "95520" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "GlobalMaxTcpWindowSize" /t REG_DWORD /d "415029" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "Guid" /t REG_BINARY /d "6c235f05c156de48a3b844ebc7bdf782" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "Guid" /t REG_BINARY /d "46790396679b6e45b95f8817359b9e2a" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "Hidden" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "HostsPriority" /t REG_DWORD /d "572" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "IPEnableRouter" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "IRPStackSize" /t REG_DWORD /d "32" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "IRPStackSize" /t REG_DWORD /d "32" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "IRPStackSize" /t REG_DWORD /d "50" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "IRPStackSize" /t REG_DWORD /d "50" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "IRPStackSize" /t REG_DWORD /d "80" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "IRPStackSize" /t REG_DWORD /d "100" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "KeepAliveInterval" /t REG_DWORD /d "1000" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "KeepAliveTime" /t REG_DWORD /d "7200000" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "Lmannounce" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "LocalPriority" /t REG_DWORD /d "91" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxCmds" /t REG_DWORD /d "30" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxCmds" /t REG_DWORD /d "100" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxCmds" /t REG_DWORD /d "2048" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxConnectionsPer1_0Server" /t REG_DWORD /d "6" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxConnectionsPer1_0Server" /t REG_DWORD /d "22" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxConnectionsPer1_0Server" /t REG_DWORD /d "4095" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxConnectionsPerServer" /t REG_DWORD /d "6" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxConnectionsPerServer" /t REG_DWORD /d "22" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxConnectionsPerServer" /t REG_DWORD /d "4095" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxFreeTcbs" /t REG_DWORD /d "415030" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxHashTableSize" /t REG_DWORD /d "4096" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxMpxCt" /t REG_DWORD /d "125" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "MaxMpxCt" /t REG_DWORD /d "125" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxMpxCt" /t REG_DWORD /d "2048" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxThreads" /t REG_DWORD /d "30" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxThreads" /t REG_DWORD /d "100" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxUserPort" /t REG_DWORD /d "415028" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "MaxWorkItems" /t REG_DWORD /d "8192" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "NetbtPriority" /t REG_DWORD /d "45" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "NullSessionPipes" /t REG_MULTI_SZ /d "" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "NullSessionPipes" /t REG_MULTI_SZ /d "" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "Path" /t REG_SZ /d "C:\Program Files\Epic Games\Fortnite\FortniteGame\Binaries\Win64\FortniteClient-Win64-Shipping.exe" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "QualifyingDestinationThreshold" /t REG_DWORD /d "3" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "RequireSecuritySignature" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "requiresecuritysignature" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "restrictnullsessaccess" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "restrictnullsessaccess" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "ServiceDll" /t REG_EXPAND_SZ /d "%%SystemRoot%%\System32\srvsvc.dll" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "ServiceDll" /t REG_EXPAND_SZ /d "%%SystemRoot%%\System32\srvsvc.dll" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "ServiceDllUnloadOnStop" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "ServiceDllUnloadOnStop" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "SharingViolationDelay" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "SharingViolationRetries" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "Size" /t REG_DWORD /d "3" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "Size" /t REG_DWORD /d "3" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "SizReqBuf" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "SizReqBuf" /t REG_DWORD /d "17238" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "SizReqBuf" /t REG_DWORD /d "17424" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanServer\Parameters" /v "SizReqBuf" /t REG_DWORD /d "17424" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "SizReqBuf" /t REG_DWORD /d "25344" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "SizReqBuf" /t REG_DWORD /d "65535" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\lanmanserver\parameters" /v "SizReqBuf" /t REG_DWORD /d "65535" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "SizReqBuf" /t REG_DWORD /d "95268" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "srvcomment" /t REG_SZ /d "" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "SynAttackProtect" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "TcpAckFrequency" /t REG_DWORD /d "18" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "TCPDelAckTicks" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "TCPMaxDataRetransmissions" /t REG_DWORD /d "7" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "TcpMaxDupAcks" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "TcpMaxDupAcks" /t REG_DWORD /d "2" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "TCPNoDelay" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "TcpNoDelay" /t REG_DWORD /d "64" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "TcpTimedWaitDelay" /t REG_DWORD /d "30" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "TcpWindowSize" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters" /v "Version" /t REG_SZ /d "1.9.4" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanServer\Parameters\FsctlAllowlist" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DefaultReceiveWindow" /t REG_DWORD /d "1053256" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DefaultSendWindow" /t REG_DWORD /d "7878468" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DirectoryCacheEntriesMax" /t REG_DWORD /d "22" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DisableBandwidthThrottling" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanWorkstation\Parameters" /v "DisableBandwidthThrottling" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DisableLargeMTU" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "DisableLargeMtu" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanWorkstation\Parameters" /v "DisableLargeMtu" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "EnablePlainTextPassword" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "EnableSecuritySignature" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "EnableSecuritySignature" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "EnableWsd" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "FileInfoCacheEntriesMax" /t REG_DWORD /d "100" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "FileNotFoundCacheEntriesMax" /t REG_DWORD /d "296" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "KeepConn" /t REG_DWORD /d "86400" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanWorkstation\Parameters" /v "KeepConn" /t REG_DWORD /d "86400" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "MaxCmds" /t REG_DWORD /d "30" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "MaxCmds" /t REG_DWORD /d "100" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\lanmanworkstation\parameters" /v "MaxCmds" /t REG_DWORD /d "100" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanWorkstation\Parameters" /v "MaxCmds" /t REG_DWORD /d "100" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "MaxCmds" /t REG_DWORD /d "2048" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "MaxCollectionCount" /t REG_DWORD /d "32" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanWorkstation\Parameters" /v "MaxCollectionCount" /t REG_DWORD /d "32" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "MaxThreads" /t REG_DWORD /d "30" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "MaxThreads" /t REG_DWORD /d "100" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\lanmanworkstation\parameters" /v "MaxThreads" /t REG_DWORD /d "100" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanWorkstation\Parameters" /v "MaxThreads" /t REG_DWORD /d "100" /f
    Reg.exe add "HKLM\System\CurrentControlSet\services\LanmanWorkstation\Parameters" /v "ReconnectTimeout" /t REG_DWORD /d "5" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "RequireSecuritySignature" /t REG_DWORD /d "0" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "ServiceDll" /t REG_EXPAND_SZ /d "%%SystemRoot%%\System32\wkssvc.dll" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "ServiceDllUnloadOnStop" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "UseLockReadUnlock" /t REG_DWORD /d "1" /f
    Reg.exe add "HKLM\System\CurrentControlSet\Services\LanmanWorkstation\Parameters" /v "UtilizeNtCaching" /t REG_DWORD /d "0" /f